apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ingress-controller.fullname" . }}
  labels:
    app: nginx-ingress
    k8s-app: {{ include "ingress-controller.fullname" . }}
    process: server
    product: platform
    tier: private
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ingress-controller.fullname" . }}
  minReplicas: {{ .Values.spec.replicas  }}
  maxReplicas: 30













